inherit_gem:
  rubocop-lazy-config: rubocop.yml

AllCops:
  TargetRubyVersion: 4.0.5
  StringLiteralsFrozenByDefault: true
  Exclude:
    - !bin/test
    - bin/{hanami,rake}

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
